import "./globals.css";
import NavbarComponente from "@/components/NavbarComponente";

export const metadata = {
  title: "Club de Córdoba Central Córdoba",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es"> 
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="/logonew2.png" type="image/x-icon" sizes="256x235"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link 
          href="https://fonts.googleapis.com/css2?family=Montserrat&family=Inter&display=swap" 
          rel="stylesheet" 
        />
      </head>
      <body>
        <NavbarComponente />
        {children}
      </body>
    </html>
  );
}
